# Load Quartus II Tcl Project package
package require ::quartus::project

set_global_assignment -name FAMILY "Cyclone V"
set_global_assignment -name DEVICE 5CSEMA5F31C6
set_global_assignment -name DEVICE_FILTER_PACKAGE FBGA
set_global_assignment -name DEVICE_FILTER_PIN_COUNT 896
set_global_assignment -name RESERVE_ALL_UNUSED_PINS "AS INPUT TRI-STATED"
set_global_assignment -name FMAX_REQUIREMENT "50 MHz "
set_global_assignment -name RESERVE_NCEO_AFTER_CONFIGURATION "USE AS REGULAR IO"
set_global_assignment -name CYCLONEII_RESERVE_NCEO_AFTER_CONFIGURATION "USE AS REGULAR IO"

set_global_assignment -name STRATIX_DEVICE_IO_STANDARD "3.3-V LVTTL"

set_location_assignment PIN_AF14 -to fpgaGlobalClock

set_location_assignment PIN_AB23 -to n_SedSeg3_SedamSegDisplej_Segment_A
set_location_assignment PIN_AE29 -to n_SedSeg3_SedamSegDisplej_Segment_B
set_location_assignment PIN_AD29 -to n_SedSeg3_SedamSegDisplej_Segment_C
set_location_assignment PIN_AC28 -to n_SedSeg3_SedamSegDisplej_Segment_D
set_location_assignment PIN_AD30 -to n_SedSeg3_SedamSegDisplej_Segment_E
set_location_assignment PIN_AC29 -to n_SedSeg3_SedamSegDisplej_Segment_F
set_location_assignment PIN_AC30 -to n_SedSeg3_SedamSegDisplej_Segment_G

set_location_assignment PIN_AE26 -to n_SedSeg1_SedamSegDisplej_Segment_A
set_location_assignment PIN_AE27 -to n_SedSeg1_SedamSegDisplej_Segment_B
set_location_assignment PIN_AE28 -to n_SedSeg1_SedamSegDisplej_Segment_C
set_location_assignment PIN_AG27 -to n_SedSeg1_SedamSegDisplej_Segment_D
set_location_assignment PIN_AF28 -to n_SedSeg1_SedamSegDisplej_Segment_E
set_location_assignment PIN_AG28 -to n_SedSeg1_SedamSegDisplej_Segment_F
set_location_assignment PIN_AH28 -to n_SedSeg1_SedamSegDisplej_Segment_G

set_location_assignment PIN_AJ29 -to n_SedSeg2_SedamSegDisplej_Segment_A
set_location_assignment PIN_AH29 -to n_SedSeg2_SedamSegDisplej_Segment_B
set_location_assignment PIN_AH30 -to n_SedSeg2_SedamSegDisplej_Segment_C
set_location_assignment PIN_AG30 -to n_SedSeg2_SedamSegDisplej_Segment_D
set_location_assignment PIN_AF29 -to n_SedSeg2_SedamSegDisplej_Segment_E
set_location_assignment PIN_AF30 -to n_SedSeg2_SedamSegDisplej_Segment_F
set_location_assignment PIN_AD27 -to n_SedSeg2_SedamSegDisplej_Segment_G

set_location_assignment PIN_AF9 -to DIP_Switch_sw_1
set_location_assignment PIN_AF10 -to DIP_Switch_sw_2
set_location_assignment PIN_AD11  -to DIP_Switch_sw_3
set_location_assignment PIN_AD12 -to DIP_Switch_sw_4
set_location_assignment PIN_AE11 -to DIP_Switch_sw_5
set_location_assignment PIN_AC9 -to DIP_Switch_sw_6
set_location_assignment PIN_AD10 -to DIP_Switch_sw_7
set_location_assignment PIN_AE12  -to DIP_Switch_sw_8

set_location_assignment PIN_W15  -to n_SW2_0
set_location_assignment PIN_AA15 -to n_SW1_0
set_location_assignment PIN_Y16  -to n_RST_0
set_location_assignment PIN_AA14 -to n_SW0_0

set_location_assignment PIN_V17  -to LED8_0
set_location_assignment PIN_W19  -to LED5_0
set_location_assignment PIN_Y19  -to LED4_0
set_location_assignment PIN_V18  -to LED7_0
set_location_assignment PIN_W17  -to LED6_0
set_location_assignment PIN_Y21  -to LED1_0
set_location_assignment PIN_W20  -to LED3_0
set_location_assignment PIN_W21  -to LED2_0

export_assignments